name: lucknow_home_services
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  intl: ^0.18.0
  shared_preferences: ^2.0.20
  connectivity_plus: ^3.0.3
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  path_provider: ^2.0.14
  url_strategy: ^0.2.0
  image_picker: ^0.8.7+1
  cached_network_image: ^3.2.3
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.4.0+7
  geolocator: ^9.0.2
  url_launcher: ^6.1.11
  country_code_picker: ^3.0.0
  phone_number: ^1.0.0
  webview_flutter: ^4.0.7
  pin_code_fields: ^7.4.0
  flutter_widget_from_html_core: ^0.8.5+3
  flutter_typeahead: ^4.3.7
  pointer_interceptor: ^0.9.3+4
  shimmer_animation: ^2.1.0+1
  carousel_slider: ^4.2.1
  google_sign_in: ^5.3.3
  flutter_facebook_auth: ^4.4.1+1
  smooth_page_indicator: ^1.0.1
  expandable: ^5.0.1
  file_picker: ^5.2.6
  timelines: ^0.1.0
  flutter_html: ^3.0.0-alpha.6
  flutter_local_notifications: ^12.0.3
  universal_html: ^2.2.3

  flutter_inappwebview: ^5.7.2+3
  timeago: ^3.4.0
  pdf: ^3.10.1
  fwfh_selectable_text: ^0.8.3+1
  diffutil_dart: ^3.0.0
  flutter_downloader: ^1.10.2
  permission_handler: ^10.2.0
  fluttertoast: ^8.2.1
  printing: ^5.10.4
  audioplayers: ^3.0.1
  dotted_border: ^2.0.0+3
  expandable_bottom_sheet: ^1.1.1+1
  share_plus: ^6.3.1
  rect_getter: ^1.1.0
  scroll_to_index: ^3.0.1
  http_parser: ^4.0.2
  http: ^0.13.5
  path: ^1.8.2
  syncfusion_flutter_datepicker: ^20.4.44

#dependency_overrides:
#  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/
    - assets/map/
    - assets/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/font/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/font/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/font/Ubuntu-Bold.ttf
          weight: 700
